version: '3'

services:

    app:
        build: .
        container_name: app
        restart: always
        tty: true
        entrypoint: dockerize -template ./.docker/app/.env:./backend/.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        ports:
            - "3000:3000"
            - "35729:35729"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - _DB_HOST=db
            - _DB_DATABASE=code_micro_videos
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
            - rabbitmq_codeflix
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=code_micro_videos
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network

    selenium:
        image: selenium/standalone-chrome
        expose:
            - 4444
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
    rabbitmq_codeflix:
        external: true
